# Generated by Django 6.0.7 on 2026-07-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admission_number',
            field=models.CharField(blank=True, help_text='Format: 12/XXXXX (for students only)', max_length=20, null=True, unique=True),
        ),
    ]
