# Generated by Django 5.2.1 on 2026-07-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_seed_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
